# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: {{ .ImageRepo }}/open-cluster-management/registration
  workImagePullSpec: {{ .ImageRepo }}/open-cluster-management/work
